from sets import *

LVL = [
	['P0','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','C2','C4','C5','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','B1','BG','WP','BG','BG','D1','D1','D1','D1','D1','D1','D1','D1','JU','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','D1','BG','BG','BG','BG','BG','BG','BG','BG','BG','B2','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','B2','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','EE','EE','EE','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BO','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BO','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BO','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','D3','D4','BG','BG','BG','BG','BG','BG','B2','BG','BG','BO','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','E3','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BO','BG','BG','S0','BG','BG','BG','WO','BG','BG','BG','BO','BG','BG','D2','BG','EE','BG','BG','B1','BG','S1','B1','S3','BG','BO','EE','BG','BO','BG','BG','BG','BG','BG','BG','T0','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','JU','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','BG','BG','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','BG','BP','BG','BG','BG','BG','BG','BG','BG','D1','D1','D1','D1','D1'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','S3','BO','BG','BG','BG','BG','BG','BO','S1','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','D1','D1','D1','D1','D1','D1','D1','D1','D1','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG']
]

LVL_H = len(LVL)
LVL_W = len(LVL[0])

