from sets import *

LVL = [
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','B2','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BO','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BO','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BO','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','D3','D4','BG','BG','BG','BG','BG','BG','B2','BG','BG','BO','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BO','BG','BG','S0','BG','BG','BG','BG','BG','BG','BG','BO','BG','BG','D2','BG','E1','BG','BG','B1','BG','S1','B1','S3','BG','BO','E1','BG','BG','BG','BG','BG','BG','BG','BG','T0','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','S1','BG','BG','BG','BG','BG'],
	['D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','BG','BG','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1','D1'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','S3','BG','BG','BG','BG','BG','BG','BG','S1','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','D1','D1','D1','D1','D1','D1','D1','D1','D1','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG'],
	['BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG','BG']
]

LVL_H = len(LVL)
LVL_W = len(LVL[0])

